variables:
  DOCKER_REPOSITORY: "mozmeao/basket"
  DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"
  # Cannot use $DOCKER_IMAGE_TAG because it contains other variables itself.
  DOCKER_RUN_CMD: "docker run --env-file .docker-env ${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"

stages:
  - build
  - deploy-admin
  - deploy-dev
  - deploy

build-images:
  stage: build
  only:
    - master
    - stage
    - prod
    - admin
  tags:
    - meao
  script:
    - make clean
    - make build-ci
    - make push-ci
    - make test-ci

.deploy:
  stage: deploy
  tags:
    - meao
    - aws
  script:
    - bin/update-config.sh

dev:
  extends: .deploy
  stage: deploy-dev
  only:
    - master
  variables:
    NAMESPACE: basket-dev
    CLUSTERS: oregon-a oregon-b

stage:
  extends: .deploy
  only:
    - master
    - stage
  variables:
    NAMESPACE: basket-stage
    CLUSTERS: frankfurt oregon-a oregon-b

stage-admin:
  extends: .deploy
  stage: deploy-admin
  only:
    - master
    - stage
  variables:
    NAMESPACE: basket-admin-stage
    CLUSTERS: oregon-a oregon-b

admin:
  extends: .deploy
  stage: deploy-admin
  only:
    - admin
    - prod
  variables:
    NAMESPACE: basket-admin
    CLUSTERS: oregon-a oregon-b

prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: basket-prod
    CLUSTERS: frankfurt oregon-a oregon-b
