machine:
  services:
    - docker
  environment:
    # Docker
    DOCKER_REPOSITORY: quay.io/mozmar/basket
    DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CIRCLE_SHA1}"
    # MySQL
    MYSQL_DATABASE: basket
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # Django
    SECRET_KEY: ssssssssshhhhhhhhhhhhh
    DEBUG: False
    ALLOWED_HOSTS: "*"
    CELERY_ALWAYS_EAGER: True
    DATABASE_URL: mysql://root@db/basket

dependencies:
  cache_directories:
    - "~/docker"
  override:
    - docker --version
    - docker info
    - if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
    - docker build -t "$DOCKER_IMAGE_TAG" --pull=true .
    - docker pull mariadb:10.0
    - mkdir -p ~/docker; docker save -o ~/docker/image.tar "$DOCKER_REPOSITORY" mozmeao/base:python-2.7-alpine mariadb

test:
  pre:
    - env > .env
    - mkdir -p "$CIRCLE_TEST_REPORTS/django"
  override:
    - docker run -d --name db -e MYSQL_DATABASE -e MYSQL_ALLOW_EMPTY_PASSWORD mariadb:10.0
    - docker run --env-file .env --link db -v "$CIRCLE_TEST_REPORTS/django:/app/test-results" "$DOCKER_IMAGE_TAG" bin/run-tests.sh
