version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup
          command: |
            echo "export DOCKER_IMAGE_TAG=mozmeao/basket:${CIRCLE_SHA1}" >> $BASH_ENV
            mkdir -p $TEST_RESULTS
      - run:
          name: Build Image
          command: |
            docker build -t "$DOCKER_IMAGE_TAG" --pull=true .
      - run:
          name: Run Tests
          command: |
            docker run --env-file docker/envfiles/test.env --name test-run "$DOCKER_IMAGE_TAG" bin/run-tests.sh
      - run: docker cp test-run:/app/test-results $TEST_RESULTS
      - store_test_results:
          path: /tmp/test-results
